language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
install:
- npm install
- grunt --no-color
git:
  submodules: false
deploy:
- provider: npm
  email: nativescript@telerik.com
  api_key:
    secure: KISJen/tS+355itLT6eI5rBAwL9utOLDT1l8z6dJKLdt24l9LvKxhHlYI/WOCVPvNCUQ8cQAqGcVgmD+SmTpoCkBAHMml3C/zGZSwYd6Km1/1Eu0JtodbtLjLaTaPYpU+I7Z2bC6eFdb8hIrFEZhf92oQAyLCgBQJpu3ECjxXgI=
  on:
    tags: true
    all_branches: true
